# Generated by Django 4.2 on 2025-03-29 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sectors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sector",
            table="sectors",
        ),
    ]
