# Generated by Django 4.2 on 2025-03-29 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sectors", "0002_alter_sector_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sector",
            table="sector",
        ),
    ]
