# Generated by Django 4.2 on 2025-03-31 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0002_alter_grade_description"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="grade",
            table="grade",
        ),
    ]
