# Generated by Django 4.2.3 on 2023-08-25 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0005_alter_entity_address_alter_entity_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0002_alter_classification_description'),
        ('type_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthesis', models.TextField(verbose_name='Síntesis')),
                ('cause', models.TextField(blank=True, verbose_name='Causa')),
                ('scope', models.CharField(choices=[('Relevant', 'Relevante'), ('Corruption', 'Corrupción')], default='Relevant', max_length=10, verbose_name='Alcance')),
                ('occurrence_date', models.DateField(verbose_name='Fecha de ocurrencia')),
                ('status', models.CharField(choices=[('Open', 'Abierto'), ('Closed', 'Cerrado')], default='Open', max_length=10, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cerrado')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classifications.classification', verbose_name='Clasificación')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_events', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entities.entity', verbose_name='Entidad')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='type_events.type', verbose_name='Tipo de Hecho')),
            ],
            options={
                'verbose_name': 'Hecho extraordinario',
                'verbose_name_plural': 'Hechos extraordinarios',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attachments/', verbose_name='Imagen')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Hecho')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Hecho',
                'verbose_name_plural': 'Registro Hechos',
                'unique_together': {('event', 'user', 'timestamp')},
            },
        ),
    ]
