# Generated by Django 4.2.3 on 2024-01-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_attachment_event_alter_measure_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
