services:
  db:
    image: postgres:14
    container_name: postgres_hechos
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_INITDB_ARGS: "--locale=es_ES.UTF-8 --encoding=UTF8"
    ports:
      - "5433:5432"
    restart: unless-stopped # Añadido para que el servicio de BD intente reiniciarse si falla
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Comando para verificar la salud de PostgreSQL
      interval: 5s # Verifica cada 5 segundos
      timeout: 5s # Espera máximo 5 segundos para la respuesta
      retries: 5 # Intenta 5 veces antes de considerarlo fallido
      start_period: 10s # Da un tiempo inicial para que el servicio

  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: hechosextra-backend
    container_name: hechos_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: db # <--- ASEGÚRATE QUE ESTA LÍNEA ESTÉ DESCOMENTADA Y PRESENTE
    depends_on:
      db:
        condition: service_healthy # <--- MEJORA: Espera a que la BD esté saludable
    restart: unless-stopped # Añadido para que el backend intente reiniciarse

  frontend:
    # build:
    #   context: .
    #   dockerfile: ./frontend/Dockerfile
    image: hechosextra-frontend
    container_name: hechos_frontend
    ports:
      - "3005:80"
    # env_file:
    #   - .env
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
