# Generated by Django 4.2 on 2025-03-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_login",
            field=models.BooleanField(default=True, verbose_name="Sesión iniciada"),
        ),
    ]
