# Generated by Django 4.2 on 2025-03-12 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customusergroup",
            table="users_group",
        ),
    ]
