# Generated by Django 4.2 on 2025-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="failed_attempts",
            field=models.IntegerField(default=0, verbose_name="Intentos fallidos"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lock_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tiempo de espera"
            ),
        ),
    ]
