# Generated by Django 4.2 on 2025-07-05 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usersession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersession",
            options={"verbose_name": "Sesión", "verbose_name_plural": "Sesiones"},
        ),
        migrations.AlterModelTable(
            name="usersession",
            table="user_session",
        ),
    ]
