# Generated by Django 4.2 on 2025-06-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Descripción"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("number", "Número"),
                            ("date", "Fecha"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de campo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Campo adicional",
                "verbose_name_plural": "Campos adicionales",
                "db_table": "add_field",
            },
        ),
        migrations.CreateModel(
            name="EventFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(verbose_name="Valor")),
                (
                    "add_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="additional_fields.additionalfield",
                        verbose_name="Campo adicional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de campo adicional",
                "verbose_name_plural": "Valores de campos adicionales",
                "db_table": "event_field_value",
            },
        ),
    ]
