# Generated by Django 4.2 on 2025-05-31 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("additional_fields", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfieldvalue",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
                verbose_name="Hecho",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfieldvalue",
            constraint=models.UniqueConstraint(
                fields=("event", "add_field"), name="unique_event_field"
            ),
        ),
    ]
