# Generated by Django 4.2 on 2025-03-31 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("additional_fields", "0004_alter_additionalfield_field_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="additionalfield",
            table="add_field",
        ),
        migrations.AlterModelTable(
            name="eventfieldvalue",
            table="event_field_value",
        ),
    ]
