# Generated by Django 4.2 on 2025-03-31 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("type_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="type",
            table="event_type",
        ),
    ]
