# Generated by Django 4.2 on 2025-06-07 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        ("classifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("type_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synthesis", models.TextField(verbose_name="Síntesis")),
                ("cause", models.TextField(blank=True, verbose_name="Causa")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("relevant", "Relevante"),
                            ("corruption", "Corrupción"),
                        ],
                        default="relevant",
                        max_length=10,
                        verbose_name="Alcance",
                    ),
                ),
                (
                    "occurrence_date",
                    models.DateField(verbose_name="Fecha de ocurrencia"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("closed", "Cerrado")],
                        default="open",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha creado"
                    ),
                ),
                (
                    "closed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha cerrado"
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classifications.classification",
                        verbose_name="Clasificación",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cerrado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entities.entity",
                        verbose_name="Entidad",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="type_events.type",
                        verbose_name="Tipo de Hecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hecho extraordinario",
                "verbose_name_plural": "Hechos extraordinarios",
                "db_table": "event",
            },
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Medida")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measures",
                        to="events.event",
                        verbose_name="Hecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medida",
                "verbose_name_plural": "Medidas",
                "db_table": "measure",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Nombre")),
                ("content_type", models.CharField(max_length=100, verbose_name="Tipo")),
                ("data", models.BinaryField(verbose_name="Contenido")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="events.event",
                        verbose_name="Hecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
                "db_table": "attachment",
            },
        ),
    ]
