# Generated by Django 4.2.3 on 2023-08-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scope',
            field=models.CharField(choices=[('relevant', 'Relevante'), ('corruption', 'Corrupción')], default='relevant', max_length=10, verbose_name='Alcance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='description',
            field=models.TextField(verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event', verbose_name='Hecho'),
        ),
    ]
