# Generated by Django 4.2.3 on 2023-10-16 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_scope_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Hecho'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Hecho'),
        ),
    ]
