# Generated by Django 4.2 on 2025-03-31 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_delete_eventlog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attachment",
            table="attachment",
        ),
        migrations.AlterModelTable(
            name="event",
            table="event",
        ),
        migrations.AlterModelTable(
            name="measure",
            table="measure",
        ),
    ]
