# Generated by Django 4.2 on 2025-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="description",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
    ]
