# Generated by Django 4.2 on 2025-05-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="Llave")),
                ("model_name", models.CharField(max_length=255, verbose_name="Modelo")),
            ],
            options={
                "verbose_name": "Llave de modelo",
                "verbose_name_plural": "Llaves de modelos",
                "db_table": "model_key",
            },
        ),
    ]
