# Generated by Django 4.2.3 on 2023-08-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_alter_municipality_options_alter_province_options_and_more'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id_entity', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.municipality', verbose_name='Municipio')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sectors.sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
