# Generated by Django 4.2 on 2025-05-31 22:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("sectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_entity",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "El código debe contener solo dígitos."
                            )
                        ],
                        verbose_name="Código",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.municipality",
                        verbose_name="Municipio",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sectors.sector",
                        verbose_name="Sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidad",
                "verbose_name_plural": "Entidades",
                "db_table": "entity",
            },
        ),
    ]
