# Generated by Django 4.2.3 on 2023-08-05 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id_entity',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+$', 'El código debe contener solo dígitos.')], verbose_name='Código'),
        ),
    ]
