# Generated by Django 4.2.3 on 2023-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_entity_id_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.TextField(null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
    ]
