# Generated by Django 4.2.3 on 2023-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_entity_address_alter_entity_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
    ]
