# Generated by Django 4.2 on 2025-03-29 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0005_alter_entity_address_alter_entity_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="entity",
            table="entity",
        ),
    ]
