# Generated by Django 4.2.3 on 2023-08-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Descripción'),
        ),
    ]
