# Generated by Django 4.2 on 2025-01-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "locations",
            "0002_alter_municipality_options_alter_province_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="province",
            name="description",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
    ]
