# Generated by Django 4.2 on 2025-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_alter_municipality_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
    ]
