# Generated by Django 4.2 on 2025-03-31 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_alter_municipality_description"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="municipality",
            table="municipality",
        ),
        migrations.AlterModelTable(
            name="province",
            table="province",
        ),
    ]
