# Generated by Django 4.2 on 2025-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Descripción"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("number", "Número"),
                            ("date", "Fecha"),
                            ("boolean", "Booleano"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de campo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Campo adicional",
                "verbose_name_plural": "Campos adicionales",
            },
        ),
    ]
