# Generated by Django 4.2 on 2025-01-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_delete_eventlog"),
        ("additional_fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAdditionalFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(verbose_name="Valor")),
                (
                    "add_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="additional_fields.additionalfield",
                        verbose_name="Campo adicional",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Hecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de campo adicional",
                "verbose_name_plural": "Valores de campos adicionales",
            },
        ),
        migrations.AddConstraint(
            model_name="eventadditionalfieldvalue",
            constraint=models.UniqueConstraint(
                fields=("event", "add_field"), name="unique_event_add_field"
            ),
        ),
    ]
